title: Gwendal Fouché
description: Portfolio
baseurl: ""
url: "https://gwendalfouche.github.io"
theme: jekyll-theme-minimal

# Autres configs optionnelles
author: Gwendal Fouché
email: gwendal.fouche@gmail.com
